language: rust
sudo: false
matrix:
  include:
  - rust: stable
addons:
  apt:
    packages:
    - libblas-dev
    - liblapacke-dev
cache: cargo
before_install:
# on Ubuntu, blas includes cblas, and libcblas.so doesn't exist
- sed -i.bak s/=cblas/=blas/ libblas/build.rs
