[package]
name = "lutario"
version = "0.1.0"
authors = ["Fei Yuan <yuan@nscl.msu.edu>"]

[features]
default = ["libblas"]
libblas = ["netlib-src"]
accelerate = ["blas/accelerate", "lapack/accelerate"]
openblas = ["blas/openblas", "lapack/openblas"]

[dependencies]
any_key = "0.1.0"
blas = { version = "0.17.0", default-features = false }
byteorder = "1.1.0"
conv = "0.3.3"
debugit = "0.1.2"
error-chain = "0.11.0"
flate2 = { version = "0.2.20", features = ["zlib"], default-features = false }
fnv = "1.0.5"
lapack = { version = "0.13.1", default-features = false }
num = "0.1.40"
quick-error = "1.2.1"
stable_deref_trait = "1.0.0"
take_mut = "0.2.0"
xz2 = "0.1.3"

# despite the name this is not actually Netlib BLAS because we enabled "system"
[dependencies.netlib-src]
version = "0.7.0"
optional = true
default-features = false
features = ["system"]

[profile.release]
debug = true
