name: build
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install liblapacke-dev
      - run: |
          echo LIBRARY_PATH="$HOME/.local/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
      - # on Ubuntu, blas includes cblas, and libcblas.so doesn't exist
        run: |
          mkdir -p "$HOME/.local/lib"
          ln -fs /usr/lib/*/libblas.so "$HOME/.local/lib/libcblas.so"
      - run: |
          curl -fsLS https://github.com/xrf/sg-ode/archive/2.0.0.tar.gz | tar xz
          make -C sg-ode-* PREFIX="$HOME/.local" install
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -v --all-features -- --nocapture --skip slowtest_
